development:
  adapter: postgresql
  encoding: unicode
  database: dbanxiety_development
  pool: 5
  username: dbanxiety
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: dbanxiety_test
  pool: 5
  username: dbanxiety
  password: password
